#!/usr/bin/env python3

import numpy as np
import networkx as nx

from .utils import seeded, PLACEHOLDER
from numpy.random import Generator

from .graphs.constants import *
from .display import *

class Population:
    def sample(self, n: int):
        return [self.get() for _ in range(n)]
    
    def get(self):
        pass
    
    @seeded
    def __init__(self, seed = None, rng: Generator = None):
        self.seed = seed
        self.rng = rng
    
class NormalPopulation(Population):
    def __init__(self, mean, var, seed=None):
        super().__init__(seed)
        self.mean = mean
        self.var = \
            var * np.identity(2) if isinstance(var, (int, float)) else \
            [[var[0], 0], [0, var[1]]] if len(var) == 2 else \
            var
    
    def get(self):
        return tuple(self.rng.multivariate_normal(self.mean, self.var))
    
class UniformPopulation(Population):
    def __init__(self, bbox = [0, 0, 1, 1], seed=None):
        super().__init__(seed)
        self.bbox = (bbox[0], bbox[2]), (bbox[1], bbox[3])
    
    def get(self):
        return tuple(self.rng.uniform(*bounds) for bounds in self.bbox)
            
class MixedPopulation(Population):
    def __init__(self, populations, weights: list[float] = None, seed=None):
        if weights is None:
            weights = np.ones(len(populations)) / len(populations)
        else:
            weights = np.asarray(weights)
            weights = weights / sum(weights)
            
        super().__init__(seed)
        
        self.populations = [
            params if isinstance(params, Population) else \
            NormalPopulation(*params, seed=seed) if len(params) == 2 else \
            UniformPopulation(*params, seed=seed)
            for params in populations if isinstance(params, (Population, tuple))
        ]
        self.weights = weights

    def get(self):
        p : Population = self.rng.choice(self.populations, p=self.weights)
        return p.get()     

@seeded
def randint(max_i = 10000, min_i = 1, seed = None, rng: Generator = None):
    def randint_():
        guess =  None
        while guess is None or guess > max_i or guess < min_i:
            guess = int(rng.normal((min_i + max_i) / 2, (max_i - min_i) / 4))
        return guess
    
    return randint_

@seeded
def randfloat(min_f = 0, max_f = 1, seed = None, rng: Generator = None):
    def randfloat_():
        return rng.uniform(min_f, max_f)
    
    return randfloat_

def get_color_map(num_colors, pattern: bool | list = None):    
    import distinctipy
    from itertools import cycle
    
    if pattern == True:
        pattern = ['/', '\\', '|', '-', '+', 'x', 'o', 'O', '.', '*']

    colors = distinctipy.get_colors(num_colors, pastel_factor=0.0)  # Disable pastel tones for higher contrast

    hatches = cycle(pattern) if pattern else None
    
    return list(zip(colors, hatches)) if hatches else colors

from shapely.geometry import Polygon

@seeded
def make_random_points(num: int, boundary: Polygon | tuple = None, generator: Population = None, attrs: dict = {}, seed: int = None):
    from shapely.geometry import box, Point

    if not isinstance(boundary, Polygon):
        boundary = box(*boundary) if boundary else box(-num / 2, -num / 2, num / 2, num / 2)
    
    if generator is None:
        generator = (
            UniformPopulation(
                boundary.bounds,
                seed=seed
            )
        )
    
    points = {}
    while len(points) < num:
        point = generator.get()
        if boundary.contains(Point(*point)):
            points[point] = {
                attr : gen() for attr, gen in attrs.items()
            }
    
    print(f"Generated {num} points (seed: {seed})")
    
    return [{
        LONGITUDE: x,
        LATITUDE: y,
        **attrs
    } for (x, y), attrs in points.items()]

@seeded
def make_voronoi(points = int | list[dict], seed = None, boundary: Polygon = None, **kwargs):
    """
    Parameters
    ----------
    points : int | list[dict]
        Points are either a list of cell descriptions (dicts) or a number of random points to be generated according to provided generator
    
    boundary : Polgon | tuple | None
        boudary is either a polygon, a tuple representing a box, or undefined in which case a bounding box is generated around the provided points

    seed : int
        seed is auto-generated by default and is used by the generator
    generator : gen
        implicitly created by the wrapper, also auto-generated by default. Both are passed to the make_points function
    
    Returns
    -------
    G : networkx graph
        voronoi cells (generated or provided) are EMBEDED in the *dual graph* as a geomtery attribute
    """
    
    from .utils import make_convex, get_midpoint
    from scipy.spatial import Voronoi
    from shapely.geometry import box, Polygon, Point, MultiPolygon
    from collections import defaultdict
    
    if isinstance(points, int):
        points = make_random_points(points, boundary=boundary, seed=seed, **kwargs)
    
    node_data = points
    points = [(d[LONGITUDE], d[LATITUDE]) for d in points]
    
    if not boundary:
        min_coords = np.min(points, axis=0)
        max_coords = np.max(points, axis=0)
        
        MAX = np.max(max_coords-min_coords, axis=0)
        PAD =  MAX / 20  # Bounding box padding
        
        boundary = box(min_coords[0]-PAD, min_coords[1]-PAD,
                max_coords[0]+PAD, max_coords[1]+PAD)
        
    elif isinstance(boundary, tuple):
        boundary = box(*boundary)

    G_dual = nx.Graph()    

    vor = Voronoi(points)
    
    # If the cell descriptors don't provide geometry, it is ingerited from the voronoi diagram
    # Otherwise the generated diagram is used to create the dual and afterwards the geometry is restored
    # This way we allow our maps to contain non-connected and even non-planar geometry
    save_geom = {}
    
    MID = Point(np.average(points, axis=0))
    LINE = max(boundary.bounds) * 50  # Length for extending infinite edges
    
    # Step 1: Handle infinite ridges
    infinite = defaultdict(list)
    for (p1, p2), (v1, v2) in zip(vor.ridge_points, vor.ridge_vertices):
        if v1 == -1 or v2 == -1:
            midpoints = get_midpoint(vor.points[p1], vor.points[p2], LINE)
            mid = max(midpoints, key=lambda p: Point(p).distance(MID)) 
            infinite[vor.point_region[p1]].append(mid)
            infinite[vor.point_region[p2]].append(mid)
    
    # Step 2: Create valid polygons for each cell
    for i, data in enumerate(node_data):
        region_idx = vor.point_region[i]
        region = vor.regions[region_idx]
        
        if not region:
            raise ValueError(f'Invalid region {i + 1}')
        
        # Case 1: Finite Voronoi cell
        if -1 not in region:
            cell_poly = Polygon(vor.vertices[region])
        # Case 2: Infinite Voronoi cell
        else:
            finite_verts = [vor.vertices[v] for v in region if v != -1]
            
            cell_poly = make_convex(finite_verts + infinite[region_idx]) or Polygon(finite_verts)
        
        # Final validation and clipping
        if cell_poly and cell_poly.is_valid:
            cell_poly = cell_poly.intersection(boundary)
            if not cell_poly.is_empty:
                if cell_poly.geom_type == 'MultiPolygon':
                    print('Clipping issue:', region)
                    cell_poly = max(cell_poly.geoms, key=lambda p: p.area)
                
                if cell_poly.geom_type == 'Polygon':
                    # Indexes start from 1, following the METIS convention
                    
                    if geo := data.get(GEOMETRY_KEY):
                        save_geom[i+1] = geo
                    data[GEOMETRY_KEY] = cell_poly
                    
                    G_dual.add_node(i + 1, **data)
                    continue
        
        print('Bad region:', region)
    
    # Funciton used to detect voronoi cell borders to generate the dual graph, only workd for voronoi cells
    def dist(p1, p2):
        if not p1 or not p2:
            return None
        
        poly1 : MultiPolygon = G_dual.nodes[p1][GEOMETRY_KEY]
        poly2 : MultiPolygon = G_dual.nodes[p2][GEOMETRY_KEY]
        
        intersection = poly1.boundary.intersection(poly2.boundary)
        
        if intersection.is_empty:
            return None
        
        if intersection.geom_type == "MultiLineString":
            return sum(linestring.length for linestring in intersection.geoms)
        else:
            return intersection.length
    
    # O(N^2) Dual graph construction
    try:
        all_edges = [(p1 + 1, p2 + 1, {EDGE_ATTR: int(d * (10 ** PERCISION))}) # KaHIP only accepts integer distance
            for p1, p2 in vor.ridge_points if (d := dist(p1 + 1, p2 + 1)) is not None]
    except:
        # Debug 
        print(G_dual.nodes[1])
    
    # Restoring the original geometry
    if len(save_geom):
        for n, data in G_dual.nodes(data=True):
            data[GEOMETRY_KEY] = save_geom[n]
        
    G_dual.add_edges_from(
        (p1 + 1, p2 + 1, {EDGE_ATTR: int(d * (10 ** PERCISION))})
        for p1, p2 in vor.ridge_points if (d := dist(p1 + 1, p2 + 1)) is not None
    )   
    
    if not nx.is_connected(G_dual):
        G_dual.add_edges_from(
            (p1, p2, data) for p1, p2, data in all_edges if not nx.has_path(G_dual, p1, p2) or nx.dijkstra_path_length(G_dual, p1, p2, EDGE_ATTR) > 1000
        )  
    
    return G_dual

if __name__ == "__main__":
    
    ALGORITHM = {
        "voronoi": make_voronoi,
        "points": make_random_points
    }    
    
    def init():
        import argparse
        parser = argparse.ArgumentParser(description='Geometry generator')

        # --Positional arguments--
        
        parser.add_argument('algorithm', choices = ALGORITHM.keys(),
                        metavar='algorithm',
                        help='Type of geometry to generate (choices: %(choices)s)')
        parser.add_argument('n', type = str,
                        help='Number of faces or input file (for voronoi) or points (otherwise)')

        # --Optional arguments--
        
        # Ignored if input file is passed
        parser.add_argument('-W', '--width', type=float,
                        help='Width of the space (default: %(default)s)')
        parser.add_argument('-H', '--height', type=float,
                        help='Height of the space (default: %(default)s)')
        parser.add_argument('-WH', '--size', type=float, default=10.0,
                        help='Height and Width of the space (default: %(default)s)')
        parser.add_argument('-P', '--max_population', type=int, default=10000,
                        help='Max population for single node (default: %(default)s)')
        parser.add_argument('-s', '--seed', type=int,
                        help='Generation seed')
        
        # Display options
        parser.add_argument('-q', '--quiet', action='store_true',
                        help='Supress graph output')
        parser.add_argument('-c', '--color', action='store_true',
                        help='Color graph')
        parser.add_argument('-F', '--fancy', action='store_true',
                        help='Add hatches to graph')
        parser.add_argument('-L', '--label', type=str,
                        help='Label graph feature')
        
        parser.add_argument('-o', '--output', type=str,
                        help=f"Output filename, (default: {PLACEHOLDER})")
        
        return parser.parse_args()
    
    args = init()
    
    G = nx.Graph()
    
    if args.n.isdigit():
        # If n is int, new points are generated
        
        seed = args.seed or np.random.SeedSequence().entropy
        print('Seed used:', seed)
        
        w = args.width or args.size
        h = args.height or args.size
        
        G = ALGORITHM[args.algorithm](
            int(args.n), 
            boundary = (boundary := (-w/2, -h/2, w/2, h/2)),
            attrs = {
                NODE_ATTR: randint(args.max_population, seed=seed)
            },
            generator = MixedPopulation(
                *zip(*[(
                    ((point[LONGITUDE], point[LATITUDE]), point['var']), 
                    point['weight']
                )
                for point in make_random_points(
                    max(int(np.sqrt(int(args.n))), 1), 
                    boundary=boundary, 
                    attrs={
                        'weight' : randint(100, seed=seed),
                        'var' : randfloat(max(w, h) / 10, max(w, h) / 2, seed=seed)
                    },
                    seed=seed
                )]),
                seed=seed
            ),
            seed=seed
        )
        
    else:
        # Otherwise generate dual graph from provided voronoi
        import geopandas as gpd

        # Only voronoi makes sense in this case
        G = ALGORITHM["voronoi"](gpd.read_file(args.n).to_dict('records'))
    
    if isinstance(G, nx.Graph):
        from .graphs import MetisFormat
        MetisFormat().write(G, filename=args.output)
    
    if not args.quiet:
        from .display import *
        display(
            G, 
            label = args.label, 
            color = args.color, 
            hatch = args.fancy
        )